#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("shipmonitor.Resource", IsApplication=true)]

namespace shipmonitor
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int detail_parent_background = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int lineartextview_layoutTitlebackground = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int lineartextview_layoutbackground = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int lineartextview_titlelabletextcolor = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050001
			public const int boattray_labMarginRight = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int boattray_txtviewMargin = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int linearLayout_txtviewDefaultHeight = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int main_signmagrin = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int allshiplistview_parent = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int allshiplistview_round = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int allshiplistview_round_yellow = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int AppIcon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int AppIcon2 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int AppIcon7 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int backBtn = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int background_view_rounded_top = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int baseInfoBtnDisable = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int baseInfoBtnNormal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int baseInfoBtnPress = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int cellButtom = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int cellMiddle = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int cellTop = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int costDetailBottom = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int costDetailMiddle = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int costDetailTop = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int currentBtnDisable = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int currentBtnNormal = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int currentBtnPress = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int dashedline = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Default1 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Default568h = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int expenseBtnDisable = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int expenseBtnNormal = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int expenseBtnPress = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int gasBtnDisable = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int gasBtnNormala2x = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int gasBtnPressa2x = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int goodsOwnerBtnDisablea2x = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int goodsOwnerBtnNormala2x = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int goodsOwnerBtnPressa2x = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int Icon = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int icon_marka2x = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int LG = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int LG2 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int liebiaotouxiang = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int line1a2x = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int linea2x = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int Login_Bk2a2x = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int Login_Bka2x = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int Login_Defaulta2x = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int Login_Find_Na2x = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int Login_Login_Ha2x = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int Login_Login_Na2x = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int Login_NameBka2x = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int Login_Reset_Ha2x = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int Login_Reset_Na2x = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int Login_Selecteda2x = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int logoa2x = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int messageInputNormala2x = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int messageInputSelecteda2x = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int moreBtna2x = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int msgBtnDisablea2x = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int msgBtnNormala2x = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int msgBtnPressa2x = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int nav_title_ios7a2x = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int nav_titlea2x = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int portBtnDisablea2x = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int portBtnNormala2x = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int portBtnPressa2x = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int portServiceBtnDisablea2x = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int portServiceBtnNormala2x = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int portServiceBtnPressa2x = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int projectFollowBtnDisablea2x = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int projectFollowBtnNormala2x = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int projectFollowBtnPressa2x = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int pwdTxNormala2x = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int pwdTxSelecteda2x = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int sendMsgNormala2x = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int sendMsgSelecteda2x = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int separateLinea2x = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int serviceBtnDisablea2x = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int serviceBtnNormala2x = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int serviceBtnPressa2x = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int ship_detail_btnback_res = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int ship_detail_btnbaseinfo_res = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int ship_detail_btncurrent_res = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int ship_detail_btnexpense_res = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int ship_detail_btngas_res = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int ship_detail_btngoodsOwner_res = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int ship_detail_btnmsg_res = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int ship_detail_btnport_res = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int ship_detail_btnprojectFollow_res = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int ship_detail_btnprotservice_res = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int ship_detail_btnservice_res = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int userNameTxNormala2x = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int userNameTxSelecteda2x = 2130837591;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08002c
			public const int basedetail_tv_attention = 2131230764;
			
			// aapt resource value: 0x7f080026
			public const int basedetail_tv_buildpay = 2131230758;
			
			// aapt resource value: 0x7f08004b
			public const int basedetail_tv_business = 2131230795;
			
			// aapt resource value: 0x7f080023
			public const int basedetail_tv_bustime = 2131230755;
			
			// aapt resource value: 0x7f080027
			public const int basedetail_tv_cargoportcost = 2131230759;
			
			// aapt resource value: 0x7f08003a
			public const int basedetail_tv_contractcompany = 2131230778;
			
			// aapt resource value: 0x7f08003e
			public const int basedetail_tv_contractemail = 2131230782;
			
			// aapt resource value: 0x7f08003d
			public const int basedetail_tv_contractfax = 2131230781;
			
			// aapt resource value: 0x7f080039
			public const int basedetail_tv_contractname = 2131230777;
			
			// aapt resource value: 0x7f08003b
			public const int basedetail_tv_contractphone = 2131230779;
			
			// aapt resource value: 0x7f08003c
			public const int basedetail_tv_contracttelepone = 2131230780;
			
			// aapt resource value: 0x7f080051
			public const int basedetail_tv_dispatch = 2131230801;
			
			// aapt resource value: 0x7f08001b
			public const int basedetail_tv_dock = 2131230747;
			
			// aapt resource value: 0x7f080029
			public const int basedetail_tv_emptyrange = 2131230761;
			
			// aapt resource value: 0x7f080019
			public const int basedetail_tv_endtime = 2131230745;
			
			// aapt resource value: 0x7f080016
			public const int basedetail_tv_id = 2131230742;
			
			// aapt resource value: 0x7f08002b
			public const int basedetail_tv_istime = 2131230763;
			
			// aapt resource value: 0x7f080020
			public const int basedetail_tv_lasttime = 2131230752;
			
			// aapt resource value: 0x7f08001c
			public const int basedetail_tv_load = 2131230748;
			
			// aapt resource value: 0x7f08002e
			public const int basedetail_tv_loadcompany = 2131230766;
			
			// aapt resource value: 0x7f080032
			public const int basedetail_tv_loademail = 2131230770;
			
			// aapt resource value: 0x7f080031
			public const int basedetail_tv_loadfax = 2131230769;
			
			// aapt resource value: 0x7f08002d
			public const int basedetail_tv_loadname = 2131230765;
			
			// aapt resource value: 0x7f08002f
			public const int basedetail_tv_loadphone = 2131230767;
			
			// aapt resource value: 0x7f080028
			public const int basedetail_tv_loadrange = 2131230760;
			
			// aapt resource value: 0x7f080030
			public const int basedetail_tv_loadtelepone = 2131230768;
			
			// aapt resource value: 0x7f08001e
			public const int basedetail_tv_loadtime = 2131230750;
			
			// aapt resource value: 0x7f08004e
			public const int basedetail_tv_maintenance = 2131230798;
			
			// aapt resource value: 0x7f080059
			public const int basedetail_tv_manager = 2131230809;
			
			// aapt resource value: 0x7f080015
			public const int basedetail_tv_name = 2131230741;
			
			// aapt resource value: 0x7f080040
			public const int basedetail_tv_ownercompany = 2131230784;
			
			// aapt resource value: 0x7f080044
			public const int basedetail_tv_owneremail = 2131230788;
			
			// aapt resource value: 0x7f080043
			public const int basedetail_tv_ownerfax = 2131230787;
			
			// aapt resource value: 0x7f08003f
			public const int basedetail_tv_ownername = 2131230783;
			
			// aapt resource value: 0x7f080041
			public const int basedetail_tv_ownerphone = 2131230785;
			
			// aapt resource value: 0x7f080042
			public const int basedetail_tv_ownertelepone = 2131230786;
			
			// aapt resource value: 0x7f080057
			public const int basedetail_tv_personnel = 2131230807;
			
			// aapt resource value: 0x7f08001a
			public const int basedetail_tv_port = 2131230746;
			
			// aapt resource value: 0x7f080046
			public const int basedetail_tv_proxycompany = 2131230790;
			
			// aapt resource value: 0x7f08004a
			public const int basedetail_tv_proxyemail = 2131230794;
			
			// aapt resource value: 0x7f080049
			public const int basedetail_tv_proxyfax = 2131230793;
			
			// aapt resource value: 0x7f080045
			public const int basedetail_tv_proxyname = 2131230789;
			
			// aapt resource value: 0x7f080047
			public const int basedetail_tv_proxyphone = 2131230791;
			
			// aapt resource value: 0x7f080048
			public const int basedetail_tv_proxytelepone = 2131230792;
			
			// aapt resource value: 0x7f080025
			public const int basedetail_tv_remark = 2131230757;
			
			// aapt resource value: 0x7f080054
			public const int basedetail_tv_sea = 2131230804;
			
			// aapt resource value: 0x7f080014
			public const int basedetail_tv_settime = 2131230740;
			
			// aapt resource value: 0x7f080018
			public const int basedetail_tv_starttime = 2131230744;
			
			// aapt resource value: 0x7f08002a
			public const int basedetail_tv_totalrange = 2131230762;
			
			// aapt resource value: 0x7f080017
			public const int basedetail_tv_totaltime = 2131230743;
			
			// aapt resource value: 0x7f080022
			public const int basedetail_tv_totalvoyagetime = 2131230754;
			
			// aapt resource value: 0x7f08001d
			public const int basedetail_tv_unload = 2131230749;
			
			// aapt resource value: 0x7f080034
			public const int basedetail_tv_unloadcompany = 2131230772;
			
			// aapt resource value: 0x7f080038
			public const int basedetail_tv_unloademail = 2131230776;
			
			// aapt resource value: 0x7f080037
			public const int basedetail_tv_unloadfax = 2131230775;
			
			// aapt resource value: 0x7f080033
			public const int basedetail_tv_unloadname = 2131230771;
			
			// aapt resource value: 0x7f080035
			public const int basedetail_tv_unloadphone = 2131230773;
			
			// aapt resource value: 0x7f080036
			public const int basedetail_tv_unloadtelepone = 2131230774;
			
			// aapt resource value: 0x7f08001f
			public const int basedetail_tv_unloadtime = 2131230751;
			
			// aapt resource value: 0x7f080021
			public const int basedetail_tv_voyagetime = 2131230753;
			
			// aapt resource value: 0x7f080024
			public const int basedetail_tv_waittime = 2131230756;
			
			// aapt resource value: 0x7f080003
			public const int btn_allshiplistview_icn = 2131230723;
			
			// aapt resource value: 0x7f08007c
			public const int btn_shipdetail_baseinfo = 2131230844;
			
			// aapt resource value: 0x7f080084
			public const int btn_shipdetail_current = 2131230852;
			
			// aapt resource value: 0x7f080085
			public const int btn_shipdetail_expense = 2131230853;
			
			// aapt resource value: 0x7f080082
			public const int btn_shipdetail_gas = 2131230850;
			
			// aapt resource value: 0x7f08007d
			public const int btn_shipdetail_leavemessage = 2131230845;
			
			// aapt resource value: 0x7f08007f
			public const int btn_shipdetail_owner = 2131230847;
			
			// aapt resource value: 0x7f08007e
			public const int btn_shipdetail_port = 2131230846;
			
			// aapt resource value: 0x7f080087
			public const int btn_shipdetail_projectFollow = 2131230855;
			
			// aapt resource value: 0x7f080081
			public const int btn_shipdetail_protservice = 2131230849;
			
			// aapt resource value: 0x7f080080
			public const int btn_shipdetail_service = 2131230848;
			
			// aapt resource value: 0x7f08005b
			public const int detailstilebar_tvtitle = 2131230811;
			
			// aapt resource value: 0x7f08005c
			public const int detailstilebar_view_donedetail = 2131230812;
			
			// aapt resource value: 0x7f08005d
			public const int detailstitlebar_btn_donedetail = 2131230813;
			
			// aapt resource value: 0x7f08005a
			public const int detailstitlebar_btnback = 2131230810;
			
			// aapt resource value: 0x7f080062
			public const int docklistitem_tv_company = 2131230818;
			
			// aapt resource value: 0x7f080065
			public const int docklistitem_tv_fax = 2131230821;
			
			// aapt resource value: 0x7f080061
			public const int docklistitem_tv_linkman = 2131230817;
			
			// aapt resource value: 0x7f080066
			public const int docklistitem_tv_mail = 2131230822;
			
			// aapt resource value: 0x7f08005f
			public const int docklistitem_tv_name = 2131230815;
			
			// aapt resource value: 0x7f080063
			public const int docklistitem_tv_phone = 2131230819;
			
			// aapt resource value: 0x7f080060
			public const int docklistitem_tv_port = 2131230816;
			
			// aapt resource value: 0x7f080064
			public const int docklistitem_tv_tel = 2131230820;
			
			// aapt resource value: 0x7f08005e
			public const int docklistview_lv = 2131230814;
			
			// aapt resource value: 0x7f080067
			public const int edite_leaveMessage_inputmessage = 2131230823;
			
			// aapt resource value: 0x7f080007
			public const int layout_allship_iscomplete = 2131230727;
			
			// aapt resource value: 0x7f08000f
			public const int layout_allship_profit = 2131230735;
			
			// aapt resource value: 0x7f080068
			public const int leavemessage_btn_submit = 2131230824;
			
			// aapt resource value: 0x7f080069
			public const int leavemessage_lsmessage = 2131230825;
			
			// aapt resource value: 0x7f080001
			public const int linearLayout1 = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int linearLayout2 = 2131230722;
			
			// aapt resource value: 0x7f080075
			public const int linearLayout3 = 2131230837;
			
			// aapt resource value: 0x7f080078
			public const int linearLayout4 = 2131230840;
			
			// aapt resource value: 0x7f080083
			public const int linearLayout5 = 2131230851;
			
			// aapt resource value: 0x7f080086
			public const int linearLayout6 = 2131230854;
			
			// aapt resource value: 0x7f08006e
			public const int linear_ct_ly_context = 2131230830;
			
			// aapt resource value: 0x7f08006d
			public const int linear_ct_ly_parent = 2131230829;
			
			// aapt resource value: 0x7f080071
			public const int linear_ct_ly_view = 2131230833;
			
			// aapt resource value: 0x7f08006f
			public const int linear_ct_tv_lable = 2131230831;
			
			// aapt resource value: 0x7f080070
			public const int linear_ct_tv_value = 2131230832;
			
			// aapt resource value: 0x7f080079
			public const int main_btnsignin = 2131230841;
			
			// aapt resource value: 0x7f080076
			public const int main_cbkeeppass = 2131230838;
			
			// aapt resource value: 0x7f080077
			public const int main_cbkeepsign = 2131230839;
			
			// aapt resource value: 0x7f080072
			public const int main_imgicon = 2131230834;
			
			// aapt resource value: 0x7f080074
			public const int main_txtpassword = 2131230836;
			
			// aapt resource value: 0x7f080073
			public const int main_txtusername = 2131230835;
			
			// aapt resource value: 0x7f08007a
			public const int maintitle_content = 2131230842;
			
			// aapt resource value: 0x7f08007b
			public const int owner_linearlayout = 2131230843;
			
			// aapt resource value: 0x7f080000
			public const int rflv_allship_rflvallship = 2131230720;
			
			// aapt resource value: 0x7f080013
			public const int scrollView1 = 2131230739;
			
			// aapt resource value: 0x7f08004c
			public const int tableRow3 = 2131230796;
			
			// aapt resource value: 0x7f08004d
			public const int tableRow30 = 2131230797;
			
			// aapt resource value: 0x7f080050
			public const int tableRow31 = 2131230800;
			
			// aapt resource value: 0x7f080053
			public const int tableRow32 = 2131230803;
			
			// aapt resource value: 0x7f080056
			public const int tableRow33 = 2131230806;
			
			// aapt resource value: 0x7f080058
			public const int tableRow34 = 2131230808;
			
			// aapt resource value: 0x7f08004f
			public const int tableRow4 = 2131230799;
			
			// aapt resource value: 0x7f080052
			public const int tableRow5 = 2131230802;
			
			// aapt resource value: 0x7f080055
			public const int tableRow6 = 2131230805;
			
			// aapt resource value: 0x7f08000a
			public const int tv_allship_diaodu = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int tv_allship_haiwu = 2131230731;
			
			// aapt resource value: 0x7f080011
			public const int tv_allship_income = 2131230737;
			
			// aapt resource value: 0x7f08000c
			public const int tv_allship_jiwu = 2131230732;
			
			// aapt resource value: 0x7f080012
			public const int tv_allship_outlay = 2131230738;
			
			// aapt resource value: 0x7f080010
			public const int tv_allship_profit = 2131230736;
			
			// aapt resource value: 0x7f08000d
			public const int tv_allship_renshi = 2131230733;
			
			// aapt resource value: 0x7f080009
			public const int tv_allship_shangwu = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int tv_allship_status = 2131230728;
			
			// aapt resource value: 0x7f08000e
			public const int tv_allship_zongjingli = 2131230734;
			
			// aapt resource value: 0x7f080005
			public const int tv_allshiplistview_number = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int tv_allshiplistview_time = 2131230726;
			
			// aapt resource value: 0x7f080004
			public const int tv_allshiplistview_title = 2131230724;
			
			// aapt resource value: 0x7f08006c
			public const int tv_lmls_leavemessage = 2131230828;
			
			// aapt resource value: 0x7f08006b
			public const int tv_lmls_submittime = 2131230827;
			
			// aapt resource value: 0x7f08006a
			public const int tv_lmls_username = 2131230826;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int allshipinfo = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int allshiplistview = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int baseInfolayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int detailstitlebar = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int docklistview = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int docklistviewitem = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int leaveMessage = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int leaveMessageListviewItem = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int lineartextview_customcontrol = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Main = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int maintitlebar = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int owerinfoactivity = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int servingcostlayout = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int shipdetail = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int twoLinearTextview_custom = 2130903054;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070008
			public const int login_username_top_rounded = 2131165192;
			
			// aapt resource value: 0x7f070001
			public const int style_allshiplistview_tv = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int style_centertextview = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int style_detail_table = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int style_detail_textview = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int style_detail_textview_lable = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int style_detail_textview_lableTitle = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int style_detailship_imagebutton = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int style_view_cut = 2131165191;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
